spring:
#  datasource:
#    sqlite:
#      url: jdbc:sqlite:src\main\resources\static\yx_data.db
#  #    url: jdbc:sqlite:D:\yx_common\yx_data.db
#  #    url: jdbc:sqlite:/home/wqs/javaCommon/yx_data.db
#      driver-class-name: org.sqlite.JDBC
#      username:
#      password:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML

## 消息队列名称
queue:
  signet: queue.signet.${random.value}
# 处理记录时
server:
  port: 8888
  connection-timeout: 100000
  tomcat:
    max-http-post-size: -1
    max-http-header-size: -1
#  servlet:
#    context-path: /yunxi
mybatis:
  type-aliases-package: com.stamper.yx.common.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置不受校验的地址
#   /device/getAccessToken #获取token
#    /device/ws #websocket地址
#    /device/deviceCallBack/res #设备回调
#    /device/config/addConfigError  #
#    /device/config/updateAPK #更新apk
#    /device/sealRecordInfo/addEasyInfo #指纹模式上传
#    /device/sealRecordInfo/addNormalInfo #申请单模式上传
#    /device/sealRecordInfo/addAuditInfo #审计模式上传
#    /device/config/getConfigByUUID #获取配置信息
#    /device/config/updateConfigByUUID #更新配置信息
#    /device/deviceCallBack/moduleCallback #模块回调地址
#    /device/sealRecordInfo/meter #高拍仪记录上传

ignorePaths:
  Paths:
    - /device/getAccessToken
    - /device/ws
    - /device/deviceCallBack/res
    - /device/config/addConfigError
    - /device/config/updateAPK
    - /device/sealRecordInfo/addEasyInfo
    - /device/sealRecordInfo/addNormalInfo
    - /device/sealRecordInfo/addAuditInfo
    - /device/config/getConfigByUUID
    - /device/config/updateConfigByUUID
    - /device/deviceCallBack/moduleCallback
    - /device/sealRecordInfo/meter
    - /device/getAddrsBySignet

#ok.http.connect-timeout=5
#ok.http.read-timeout=30
#ok.http.write-timeout=30
## 连接池中整体的空闲连接的最大数量
#ok.http.max-idle-connections=200
## 连接空闲时间最多为 300 秒
#ok.http.keep-alive-duration=300
#因为websocket通道的垃圾池在10s秒内关闭，超时时间不能超过10s,否则通道被关闭，系统会异常
ok:
  http:
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
#是否启用rabbitMQ
#注意：配置数据源时：【driverClassName不能写成driver-class-name】【url 换成jdbc-url】
datasource:
#    sqlite:
#      jdbc-url: jdbc:sqlite:src\main\resources\static\yx_data.db
#      driver-class-name: org.sqlite.JDBC
#      username:
#      password:
    #多数据源：mysql
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Yunxi123$%^
#      password: root
      # 中海广瀛
#      password: stwin123$%^
      # 安徽晶奇
#      password: Yunxi123$%^
      # 平度城投/店子镇
#      password: Yunxi123$%^

# 隐修数据库
#      password: dogSleep123$%^
    #天津切换Oracle
#    mysql:
#      jdbc-url: jdbc:oracle:thin:@192.168.85.143:1521:XE
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      username: root
#      password: root

#服务关停:true:开启、false:关闭
#需配合host.properties中的OPEN_MYSQL同步
openType:
  mysql: true
