/*
 Navicat Premium Data Transfer

 Source Server         : Oracle_root
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.74.129:1521
 Source Schema         : ROOT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 27/03/2020 16:33:05
*/


-- ----------------------------
-- Table structure for ADDRINFO
-- ----------------------------
DROP TABLE "ROOT"."ADDRINFO";
CREATE TABLE "ROOT"."ADDRINFO" (
  "ID" NUMBER(11) NOT NULL ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) ,
  "DEVICE_ID" NUMBER(11) ,
  "LONGITUDE" VARCHAR2(25 BYTE) ,
  "LATITUDE" VARCHAR2(25 BYTE) ,
  "LOCATION" VARCHAR2(255 BYTE) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."ADDRINFO"."DEVICE_ID" IS '设备id';
COMMENT ON COLUMN "ROOT"."ADDRINFO"."LONGITUDE" IS '经度';
COMMENT ON COLUMN "ROOT"."ADDRINFO"."LATITUDE" IS '纬度';
COMMENT ON COLUMN "ROOT"."ADDRINFO"."LOCATION" IS '地址信息';

-- ----------------------------
-- Table structure for FILE_INFO
-- ----------------------------
DROP TABLE "ROOT"."FILE_INFO";
CREATE TABLE "ROOT"."FILE_INFO" (
  "ID" NUMBER(11) NOT NULL ,
  "SEAL_RECORD_INFO_ID" NUMBER(11) ,
  "ORIGINAL_NAME" VARCHAR2(100 BYTE) ,
  "FILE_NAME" VARCHAR2(100 BYTE) ,
  "PATH" VARCHAR2(100 BYTE) ,
  "RELATIVE_PATH" VARCHAR2(255 BYTE) ,
  "ABSOLUTE_PATH" VARCHAR2(255 BYTE) ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."FILE_INFO"."SEAL_RECORD_INFO_ID" IS '璁板綍id';
COMMENT ON COLUMN "ROOT"."FILE_INFO"."ORIGINAL_NAME" IS '鍘熸枃浠跺悕';
COMMENT ON COLUMN "ROOT"."FILE_INFO"."FILE_NAME" IS '鏂版枃浠跺悕';
COMMENT ON COLUMN "ROOT"."FILE_INFO"."PATH" IS '鏂囦欢閰嶇疆鍦板潃';
COMMENT ON COLUMN "ROOT"."FILE_INFO"."RELATIVE_PATH" IS '鏈瀛樺偍鐩稿璺緞';
COMMENT ON COLUMN "ROOT"."FILE_INFO"."ABSOLUTE_PATH" IS '鏈瀛樺偍缁濆璺緞';

-- ----------------------------
-- Table structure for FINGER
-- ----------------------------
DROP TABLE "ROOT"."FINGER";
CREATE TABLE "ROOT"."FINGER" (
  "ID" NUMBER(11) NOT NULL ,
  "USER_ID" NUMBER(11) ,
  "USER_NAME" VARCHAR2(20 BYTE) ,
  "DEVICE_ID" NUMBER(11) ,
  "FINGER_ADDR" NUMBER(11) ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."FINGER"."USER_ID" IS '鐢ㄦ埛ID';
COMMENT ON COLUMN "ROOT"."FINGER"."DEVICE_ID" IS '璁惧ID';
COMMENT ON COLUMN "ROOT"."FINGER"."FINGER_ADDR" IS '鎸囩汗鍦板潃';

-- ----------------------------
-- Table structure for SEAL_RECORD_INFO
-- ----------------------------
DROP TABLE "ROOT"."SEAL_RECORD_INFO";
CREATE TABLE "ROOT"."SEAL_RECORD_INFO" (
  "ID" NUMBER(11) NOT NULL ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) ,
  "DEVICE_ID" NUMBER(11) ,
  "UUID" VARCHAR2(30 BYTE) ,
  "IDENTITY" VARCHAR2(20 BYTE) ,
  "PICUSEID" NUMBER(11) ,
  "LOCATION" VARCHAR2(150 BYTE) ,
  "COUNT" NUMBER(11) ,
  "APPLICATION_ID" NUMBER(11) ,
  "IS_AUDIT" NUMBER(11) ,
  "TIME" NVARCHAR2(20) ,
  "SEAL_COUNT" NUMBER(11) ,
  "SEAL_ID" NUMBER(11) ,
  "ALARM" NUMBER(11) ,
  "FILE_ID" NUMBER(11) ,
  "SRI_TYPE" NUMBER(11) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."DEVICE_ID" IS '璁惧ID';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."PICUSEID" IS '鐢ㄥ嵃浜篒D';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."LOCATION" IS '鐢ㄥ嵃鍦板潃';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."APPLICATION_ID" IS '鐢宠鍗旾D';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."IS_AUDIT" IS '0:璇ユ潯璁板綍鏄洊绔犱笂浼犲垱寤虹殑  1:璇ユ潯璁板綍鏄璁′笂浼犲垱寤虹殑''';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."TIME" IS '鐪熷疄鐩栫珷鏃堕棿';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."SEAL_COUNT" IS '楂樻媿浠叧鑱旂殑鐩栫珷娆℃暟';
COMMENT ON COLUMN "ROOT"."SEAL_RECORD_INFO"."SEAL_ID" IS '楂樻媿浠叧鑱旂殑鍗扮珷ID';

-- ----------------------------
-- Table structure for SIGNET
-- ----------------------------
DROP TABLE "ROOT"."SIGNET";
CREATE TABLE "ROOT"."SIGNET" (
  "ID" NUMBER(11) NOT NULL ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) ,
  "CORP_ID" VARCHAR2(64 BYTE) ,
  "NAME" VARCHAR2(50 BYTE) ,
  "NET_TYPE" VARCHAR2(50 BYTE) ,
  "ADDR" VARCHAR2(255 BYTE) ,
  "COUNT" NUMBER(11) ,
  "UUID" VARCHAR2(50 BYTE) ,
  "SIM_NUM" VARCHAR2(20 BYTE) ,
  "ICCID" VARCHAR2(20 BYTE) ,
  "IMSI" VARCHAR2(20 BYTE) ,
  "IMEI" VARCHAR2(20 BYTE) ,
  "TYPE" NUMBER(2) ,
  "STATUS" NUMBER(2) ,
  "SLEEP_TIME" NUMBER(11) ,
  "FINGER_PATTERN" NUMBER(1) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."SIGNET"."CORP_ID" IS '绗笁鏂逛紒涓欼D';
COMMENT ON COLUMN "ROOT"."SIGNET"."ADDR" IS '鍗扮珷鍦板潃';
COMMENT ON COLUMN "ROOT"."SIGNET"."COUNT" IS '鍑哄巶鍚庡凡浣跨敤娆℃暟';
COMMENT ON COLUMN "ROOT"."SIGNET"."ICCID" IS '鐗╄仈缃戝崱';
COMMENT ON COLUMN "ROOT"."SIGNET"."TYPE" IS '绫诲瀷';
COMMENT ON COLUMN "ROOT"."SIGNET"."STATUS" IS '鍗扮珷鐘舵€� 0:姝ｅ父 1:寮傚父 2:閿€姣�3:鍋滅敤 4:閿佸畾';
COMMENT ON COLUMN "ROOT"."SIGNET"."SLEEP_TIME" IS '浼戠湢鏃堕棿';
COMMENT ON COLUMN "ROOT"."SIGNET"."FINGER_PATTERN" IS '鎸囩汗妯″紡';

-- ----------------------------
-- Table structure for TJ_APPLICATIONS
-- ----------------------------
DROP TABLE "ROOT"."TJ_APPLICATIONS";
CREATE TABLE "ROOT"."TJ_APPLICATIONS" (
  "ID" NUMBER(11) NOT NULL ,
  "CREATE_DATE" TIMESTAMP(6) ,
  "UPDATE_DATE" TIMESTAMP(6) ,
  "DELETE_DATE" TIMESTAMP(6) ,
  "APPLICATION_ID" NUMBER(11) ,
  "TITLE" VARCHAR2(255 BYTE) ,
  "TOTAL_COUNT" NUMBER(11) ,
  "NEED_COUNT" NUMBER(11) ,
  "DEVICE_ID" NUMBER(11) ,
  "USER_NAME" VARCHAR2(20 BYTE) ,
  "USER_ID" NUMBER(11) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ROOT"."TJ_APPLICATIONS"."APPLICATION_ID" IS '鐢宠鍗昳d锛屼笟鍔d';
COMMENT ON COLUMN "ROOT"."TJ_APPLICATIONS"."TITLE" IS '鐢宠鏍囬';
COMMENT ON COLUMN "ROOT"."TJ_APPLICATIONS"."NEED_COUNT" IS '鐢宠宸茬敤娆℃暟';
COMMENT ON COLUMN "ROOT"."TJ_APPLICATIONS"."DEVICE_ID" IS '璁惧id';
COMMENT ON COLUMN "ROOT"."TJ_APPLICATIONS"."USER_ID" IS '鐢ㄦ埛id';

-- ----------------------------
-- Sequence structure for FILE_INFO_SEQ
-- ----------------------------
DROP SEQUENCE "ROOT"."FILE_INFO_SEQ";
CREATE SEQUENCE "ROOT"."FILE_INFO_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for FINGER_SEQ
-- ----------------------------
DROP SEQUENCE "ROOT"."FINGER_SEQ";
CREATE SEQUENCE "ROOT"."FINGER_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for SEAL_RECORD_INFO_SEQ
-- ----------------------------
DROP SEQUENCE "ROOT"."SEAL_RECORD_INFO_SEQ";
CREATE SEQUENCE "ROOT"."SEAL_RECORD_INFO_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for SIGNET_SEQ
-- ----------------------------
DROP SEQUENCE "ROOT"."SIGNET_SEQ";
CREATE SEQUENCE "ROOT"."SIGNET_SEQ" MINVALUE 1000 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for TJ_APPLICATIONS_SEQ
-- ----------------------------
DROP SEQUENCE "ROOT"."TJ_APPLICATIONS_SEQ";
CREATE SEQUENCE "ROOT"."TJ_APPLICATIONS_SEQ" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table ADDRINFO
-- ----------------------------
ALTER TABLE "ROOT"."ADDRINFO" ADD CONSTRAINT "SYS_C007010" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table FILE_INFO
-- ----------------------------
ALTER TABLE "ROOT"."FILE_INFO" ADD CONSTRAINT "SYS_C007002" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FILE_INFO
-- ----------------------------
ALTER TABLE "ROOT"."FILE_INFO" ADD CONSTRAINT "SYS_C006997" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOT"."FILE_INFO" ADD CONSTRAINT "SYS_C007022" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table FINGER
-- ----------------------------
ALTER TABLE "ROOT"."FINGER" ADD CONSTRAINT "SYS_C006998" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOT"."FINGER" ADD CONSTRAINT "SYS_C007023" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table SEAL_RECORD_INFO
-- ----------------------------
ALTER TABLE "ROOT"."SEAL_RECORD_INFO" ADD CONSTRAINT "SYS_C006999" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOT"."SEAL_RECORD_INFO" ADD CONSTRAINT "SYS_C007024" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table SIGNET
-- ----------------------------
ALTER TABLE "ROOT"."SIGNET" ADD CONSTRAINT "SYS_C007000" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOT"."SIGNET" ADD CONSTRAINT "SYS_C007025" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table TJ_APPLICATIONS
-- ----------------------------
ALTER TABLE "ROOT"."TJ_APPLICATIONS" ADD CONSTRAINT "SYS_C007001" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOT"."TJ_APPLICATIONS" ADD CONSTRAINT "SYS_C007026" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
